# -*- coding: utf-8 -*-
"""ML2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103O6s-JV7V1l_lV4x4LsL4w7JZbfpxQU
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

marks1 = ['20','30','40','50','60']

totalmarks=pd.DataFrame(marks1,columns=['totalmarks'],index=['anjali','aman','mahesh','varun','saiteja',])

totalmarks

totalmarks.to_csv('/content/TotalMarks1.csv')